import re

_RICH_JSON_COMMAND_PREFIX = "$"
_RICH_JSON_COMMAND_SUFFIX = ":"
_RICH_JSON_COMMAND_WILDCARD = "$*:*"
_RICH_JSON_COMMAND_DELIMITER = ","
_RICH_JSON_COMMAND_PATH_DELIMITER = "/"
_RICH_JSON_COMMAND_PIPE_SIGN = "|"
_RICH_JSON_COMMAND_REF = "$ref"
_RICH_JSON_COMMAND_CLONE = "clone"
_RICH_JSON_KEY_COMMAND_MEMBER = "__$_rich_json_key_commands_$__"

_RICH_JSON_ARRAY_WILDCARD = "*[*]*"
_RICH_JSON_ARRAY_DELIMITERS = re.compile(r"[\[\]]")
_RICH_JSON_ARRAY_REPLACE_SUBSTRING = "]["
_RICH_JSON_ARRAY_REPLACE_NEWSTRING = "]|["

_RICH_JSON_CONSTRUCTOR_SIGN = "="
_RICH_JSON_LATE_CONSTRUCTOR_SIGN = "=="
_RICH_JSON_LATE_CONSTRUCTOR_MEMBER = "__#_rich_json_construct_#__"
_RICH_JSON_INHERITANCE_SIGN = "::"

_RICH_JSON_NAME_IS_COMMAND = lambda name: name.startswith(_RICH_JSON_COMMAND_PREFIX) and _RICH_JSON_COMMAND_SUFFIX in name
_RICH_JSON_NAME_IS_CONSTRUCTOR = lambda name: _RICH_JSON_CONSTRUCTOR_SIGN in name
_RICH_JSON_NAME_IS_LATE_CONSTRUCTOR = lambda name: _RICH_JSON_LATE_CONSTRUCTOR_SIGN in name
_RICH_JSON_NAME_IS_INHERITANCE = lambda name: _RICH_JSON_INHERITANCE_SIGN in name

_RICH_JSON_INTERPOLATION_WILDCARD = "*{*}*"
_RICH_JSON_INTERPOLATION_OPENING_SIGN = "{"
_RICH_JSON_INTERPOLATION_CLOSING_SIGN = "}"